import { client } from '@/lib/prisma'
import { notFound } from 'next/navigation'

type Props = {
  params: { id: string }
}

export default async function PreviewPage({ params }: Props) {
  const website = await client.generatedWebsite.findUnique({
    where: { id: params.id },
    include: {
      ColdCallLead: true,
    },
  })

  if (!website) {
    notFound()
  }

  const content = website.content as any
  const html = content?.html || '<p>No website generated yet</p>'

  return (
    <div className="min-h-screen">
      {/* Preview Banner */}
      <div className="fixed top-0 left-0 right-0 z-50 bg-black/90 text-white px-4 py-2 text-center text-sm backdrop-blur">
        <span className="font-medium">Preview Mode</span>
        <span className="mx-2">•</span>
        <span className="text-gray-300">{website.ColdCallLead?.businessName}</span>
        <span className="mx-2">•</span>
        <span className="text-green-400">Generated by Slide</span>
      </div>
      
      {/* Website Content */}
      <iframe
        srcDoc={html}
        className="w-full min-h-screen border-0 pt-10"
        title={`Preview - ${website.ColdCallLead?.businessName}`}
        sandbox="allow-scripts allow-same-origin"
      />
    </div>
  )
}

export async function generateMetadata({ params }: Props) {
  const website = await client.generatedWebsite.findUnique({
    where: { id: params.id },
    include: { ColdCallLead: true },
  })

  if (!website) {
    return { title: 'Preview Not Found' }
  }

  return {
    title: `${website.ColdCallLead?.businessName} - Website Preview`,
    description: `Preview website for ${website.ColdCallLead?.businessName}`,
  }
}
