'use client'

type Props = {
  websiteId: string
  businessName: string
  html: string
}

export default function PreviewClient({ websiteId, businessName, html }: Props) {
  return (
    <div 
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: '#000',
        zIndex: 9999,
      }}
    >
      {/* Preview Banner */}
      <div 
        style={{
          flexShrink: 0,
          backgroundColor: 'rgba(0,0,0,0.95)',
          color: 'white',
          padding: '8px 16px',
          textAlign: 'center',
          fontSize: '14px',
          borderBottom: '1px solid #333',
        }}
      >
        <span style={{ fontWeight: 500 }}>Preview Mode</span>
        <span style={{ margin: '0 8px', opacity: 0.5 }}>•</span>
        <span style={{ color: '#9ca3af' }}>{businessName}</span>
        <span style={{ margin: '0 8px', opacity: 0.5 }}>•</span>
        <span style={{ color: '#4ade80' }}>Generated by Slide</span>
        <span style={{ margin: '0 8px', opacity: 0.5 }}>•</span>
        <a 
          href={`/client/${websiteId}/login`}
          style={{ color: '#60a5fa', textDecoration: 'underline' }}
        >
          Business Dashboard
        </a>
      </div>
      
      {/* Website Content - Full height iframe */}
      <iframe
        srcDoc={html}
        style={{
          flex: 1,
          width: '100%',
          border: 'none',
          backgroundColor: '#fff',
        }}
        title={`Preview - ${businessName}`}
        sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
      />
    </div>
  )
}
